### ISSUE TITLE
problem shutting down sbt

### ISSUE THREAD

**Issue by jcartledge** [jcartledge/sublime-worksheet#8]
Exception OSError: OSError(9, 'Bad file descriptor') in <bound method spawn.__del__ of <repl.pexpect.spawn object at 0x10d8ce7d0>> ignored
Traceback (most recent call last):
  File "./worksheet.py", line 46, in <lambda>
  File "./worksheet.py", line 55, in handle_thread
  File "./worksheet.py", line 69, in handle_finished_thread
  File "./worksheet.py", line 22, in close_repl
  File "./repl/repl.py", line 49, in close
    self.repl.close()
  File "./repl/pexpect.py", line 666, in close
    raise ExceptionPexpect ('close() could not terminate the child using terminate()')
repl.pexpect.ExceptionPexpect: close() could not terminate the child using terminate()

**Comment by jcartledge** [comment]
Oops - need to check the exception back in the plugin where close is called.
